config/routes.rb
Todo::Application.routes.draw do
  devise_for :users
  root "static_pages#index"
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    render json: Task.order(:id)
  end

  def update
    task = Task.find(params[:id])
    task.update_attributes(task_params)
    render json: task
  end

  def create
    task = Task.create(task_params)
    render json: task
  end

  private

  def task_params
    params.require(:task).permit(:done, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body> 

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a><%= link_to "TODO", root_path, class: 'navbar-brand'%></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <!-- Button trigger modal for sign up-->
            <li><%= link_to "Sign Up", "#", data: {toggle: 'modal', target: '#myModal'} %></li>
            <li><%= link_to "Log In", "#", data: {toggle: 'modal', target: '#myModalForLogIn'} %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

    <!-- Modal for Log In-->
    <div class="modal fade" id="myModalForLogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title text-center" id="myModalLabel">Log In</h4>
          </div>
          <br />
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="modal-body">
          
              <div class="field">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, class: 'col-xs-12' %>
              </div>
              <br />
              <br />
              <div class="field">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "off", class: 'col-xs-12' %>
              </div>
              <br />
              <br />
              <% if devise_mapping.rememberable? -%>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <% end -%>

              <br />
              <br />

            <%= render "devise/shared/links" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Log in", class: 'btn btn-primary' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Modal for Sign Up-->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title text-center" id="myModalLabel">Sign Up</h4>
          </div>
          <br />
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <div class="modal-body">
            <%= devise_error_messages! %>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, class: 'col-xs-12' %>
            </div>
            <br />
            <br />
            <div class="field">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", class: 'col-xs-12' %>
            </div>
            <br />
            <br />
            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: 'col-xs-12' %>
            </div>
            <br />
            <br />
            <%= render "devise/shared/links" %>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Sign up", class: 'btn btn-primary' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <form id="new-form">
      <input type="text" class="new-todo" placeholder="What needs to be done?" />
    </form>
  </header>

  <section class="main">
    <ul class="todo-list">

    </ul>
  </section>
</section>

<section class="authority">
  A <%= link_to "todo-mvc", "http://todomvc.com" %>
  application, build by
  <%= link_to "Aleks Real", "https://github.com/AlekstheRealist" %>
</section>